#ifndef UTILS_H
#define UTILS_H

typedef enum { 
    ERR_T_LEX_ERR = 1,
    ERR_T_SYNTAX_ERR = 2,
    ERR_T_SEMANTIC_ERR_UNDEFINED = 3,
    ERR_T_SEMANTIC_ERR_REDEFINITION = 4,
    ERR_T_SEMANTIC_ERR_BAD_FUNCTION_ARGS = 5,
    ERR_T_SEMANTIC_ERR_BAD_OPERAND_TYPES = 6,
    ERR_T_SEMANTIC_ERR_OTHER = 10,
    ERR_T_SEMANTIC_ERR_BUILTIN_FN_BAD_PARAM = 25,
    ERR_T_SEMANTIC_ERR_BUILTIN_FN_BAD_OPERAND_TYPES = 26,
    ERR_T_MALLOC_ERR = 99

} ERROR_TYPES;

#endif